FROM eclipse-temurin:21

LABEL mentainer="k.pradeep0491@gmail.com"

WORKDIR /app

COPY target/SpringBootDocker-Demo-0.0.1-SNAPSHOT.jar /app/springbootdocker-demo.jar

ENTRYPOINT ["java","-jar","springbootdocker-demo.jar"]
