FROM eclipse-temurin:17
LABEL mentainer="k.pradeep0491@gmail.com"
WORKDIR /app
COPY target/SpringbootRestfulwebservices-dockercompose-0.0.1-SNAPSHOT.jar /app/springbootrestfulwebservices.jar
ENTRYPOINT ["java","-jar","springbootrestfulwebservices.jar"]